# Generated by Django 4.2.16 on 2025-01-17 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('color', models.CharField(max_length=7)),
                ('completed', models.BooleanField(default=False)),
                ('notify', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='calendarapp.calendar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
