# Generated by Django 4.2.16 on 2025-01-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['deadline']},
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todos',
        ),
    ]
