# Generated by Django 4.2.16 on 2025-01-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_options_alter_todo_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='notify',
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(),
        ),
    ]
