# Generated by Django 4.2.16 on 2024-12-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['is_deleted', '-created_at']},
        ),
    ]
