# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['is_deleted', '-created_at'], 'verbose_name': '캐치비 공지사항', 'verbose_name_plural': '캐치비 공지사항'},
        ),
    ]
