# Generated by Django 4.2.16 on 2025-02-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='scheduled_lessons',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
