# Generated by Django 4.2.16 on 2025-03-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('contract', '0002_contract_is_reviewed'), ('contract', '0003_review'), ('contract', '0004_remove_contract_is_reviewed'), ('contract', '0005_academyreviewtags_coachreviewtags_lessonreviewtags_and_more'), ('contract', '0006_academyreviewtags_is_positive_and_more'), ('contract', '0007_remove_review_academy_image_and_more'), ('contract', '0008_remove_reviewimage_review')]

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyReviewTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('is_positive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'academy_review_tags',
            },
        ),
        migrations.CreateModel(
            name='CoachReviewTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('is_positive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'coach_review_tags',
            },
        ),
        migrations.CreateModel(
            name='LessonReviewTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('is_positive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lesson_review_tags',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='reviews/')),
            ],
            options={
                'db_table': 'review_image',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_rating', models.PositiveSmallIntegerField()),
                ('lesson_comment', models.CharField(max_length=500)),
                ('coach_rating', models.PositiveSmallIntegerField()),
                ('coach_comment', models.CharField(max_length=500)),
                ('academy_rating', models.PositiveSmallIntegerField()),
                ('academy_comment', models.CharField(max_length=500)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='contract.contract')),
                ('secure_academy', models.BooleanField(default=False)),
                ('secure_coach', models.BooleanField(default=False)),
                ('academy_tags', models.ManyToManyField(related_name='academy_reviews', to='contract.academyreviewtags')),
                ('coach_tags', models.ManyToManyField(related_name='coach_reviews', to='contract.coachreviewtags')),
                ('lesson_tags', models.ManyToManyField(related_name='lesson_reviews', to='contract.lessonreviewtags')),
                ('academy_images', models.ManyToManyField(related_name='academy_reviews', to='contract.reviewimage')),
                ('coach_images', models.ManyToManyField(related_name='coach_reviews', to='contract.reviewimage')),
                ('lesson_images', models.ManyToManyField(related_name='lesson_reviews', to='contract.reviewimage')),
            ],
            options={
                'db_table': 'review',
                'ordering': ['-created_at'],
            },
        ),
    ]
