# Generated by Django 4.2.16 on 2025-03-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
