# Generated by Django 4.2.16 on 2025-03-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_is_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_rating', models.PositiveSmallIntegerField()),
                ('lesson_comment', models.CharField(max_length=500)),
                ('coach_rating', models.PositiveSmallIntegerField()),
                ('coach_comment', models.CharField(max_length=500)),
                ('academy_rating', models.PositiveSmallIntegerField()),
                ('academy_comment', models.CharField(max_length=500)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='contract.contract')),
            ],
            options={
                'db_table': 'review',
                'ordering': ['-created_at'],
            },
        ),
    ]
