# Generated by Django 4.2.16 on 2025-03-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='is_reviewed',
        ),
    ]
