# Generated by Django 4.2.16 on 2025-03-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_remove_contract_is_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyReviewTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'academy_review_tags',
            },
        ),
        migrations.CreateModel(
            name='CoachReviewTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'coach_review_tags',
            },
        ),
        migrations.CreateModel(
            name='LessonReviewTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lesson_review_tags',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='academy_image',
            field=models.ImageField(null=True, upload_to='reviews/'),
        ),
        migrations.AddField(
            model_name='review',
            name='coach_image',
            field=models.ImageField(null=True, upload_to='reviews/'),
        ),
        migrations.AddField(
            model_name='review',
            name='lesson_image',
            field=models.ImageField(null=True, upload_to='reviews/'),
        ),
        migrations.AddField(
            model_name='review',
            name='secure_academy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='secure_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='academy_tags',
            field=models.ManyToManyField(related_name='academy_reviews', to='contract.academyreviewtags'),
        ),
        migrations.AddField(
            model_name='review',
            name='coach_tags',
            field=models.ManyToManyField(related_name='coach_reviews', to='contract.coachreviewtags'),
        ),
        migrations.AddField(
            model_name='review',
            name='lesson_tags',
            field=models.ManyToManyField(related_name='lesson_reviews', to='contract.lessonreviewtags'),
        ),
    ]
