# Generated by Django 4.2.16 on 2025-03-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_academyreviewtags_coachreviewtags_lessonreviewtags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyreviewtags',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coachreviewtags',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lessonreviewtags',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
    ]
