# Generated by Django 4.2.16 on 2025-03-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_academyreviewtags_is_positive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='academy_image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='coach_image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='lesson_image',
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='reviews/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contract.review')),
            ],
            options={
                'db_table': 'review_image',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='academy_images',
            field=models.ManyToManyField(related_name='academy_reviews', to='contract.reviewimage'),
        ),
        migrations.AddField(
            model_name='review',
            name='coach_images',
            field=models.ManyToManyField(related_name='coach_reviews', to='contract.reviewimage'),
        ),
        migrations.AddField(
            model_name='review',
            name='lesson_images',
            field=models.ManyToManyField(related_name='lesson_reviews', to='contract.reviewimage'),
        ),
    ]
