# Generated by Django 4.2.16 on 2025-03-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_remove_review_academy_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimage',
            name='review',
        ),
    ]
