# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_is_reviewed_squashed_0008_remove_reviewimage_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academyreviewtags',
            options={'verbose_name': '아카데미 리뷰 태그', 'verbose_name_plural': '아카데미 리뷰 태그'},
        ),
        migrations.AlterModelOptions(
            name='coachreviewtags',
            options={'verbose_name': '코치 리뷰 태그', 'verbose_name_plural': '코치 리뷰 태그'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'verbose_name': '계약', 'verbose_name_plural': '계약'},
        ),
        migrations.AlterModelOptions(
            name='lessonreviewtags',
            options={'verbose_name': '레슨 리뷰 태그', 'verbose_name_plural': '레슨 리뷰 태그'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': '리뷰', 'verbose_name_plural': '리뷰'},
        ),
        migrations.AlterModelOptions(
            name='reviewimage',
            options={'verbose_name': '리뷰 이미지', 'verbose_name_plural': '리뷰 이미지'},
        ),
    ]
