sonar.projectKey=vietman2_SweepSeries
sonar.organization=vietman2
sonar.projectName=SweepSeries
sonar.projectVersion=1.0
sonar.sources=catchb-admin,catchbweb,sweep,sweepseries
sonar.coverage.exclusions=**/*.test.tsx,**/*.test.ts,**/tests.py,**/tests/*,**/*.config.js,**/migrations/*,**/settings/*,**/wsgi.py,**/asgi.py,**/manage.py
sonar.javascript.lcov.reportPaths=catchb-admin/coverage/lcov.info,catchbweb/coverage/lcov.info,sweep/coverage/lcov.info
sonar.python.coverage.reportPaths=sweepseries/coverage.xml
