sonar.projectKey=vietman2_SweepSeries
sonar.organization=vietman2
sonar.projectName=SweepSeries
sonar.projectVersion=1.0
sonar.sources=catchb-admin,catchbweb,sweep,sweepseries
sonar.tests=catchb-admin/src,catchbweb/src,sweep/src,sweepseries
sonar.exclusions=sweepseries/**/migrations/*,**/index.ts,**/index.tsx,**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=catchb-admin/coverage/lcov.info,catchbweb/coverage/lcov.info,sweep/coverage/lcov.info
sonar.python.coverage.reportPaths=sweepseries/coverage.xml
