sonar.projectKey=vietman2_SweepSeries
sonar.organization=vietman2
sonar.projectName=SweepSeries
sonar.projectVersion=1.0
sonar.sources=catchb-admin,catchbweb,sweep,sweepseries
sonar.python.version=3.9
sonar.exclusions=**/tests.py, **/__init__.py, **/migrations/*, **/urls.py, **/apps.py, **/admin.py, **/wsgi.py, **/asgi.py, manage.py, **/settings.py, **/manage.py
sonar.coverage.exclusions=**/*.test.tsx, **/*.test.ts, **/app/**, **/constants/**, **/hooks/**, **/*.config.js, **/tests.py, **/__init__.py, **/migrations/*, **/urls.py, **/apps.py, **/admin.py, **/wsgi.py, **/asgi.py, manage.py, **/settings.py, **/manage.py
sonar.javascript.lcov.reportPaths=catchb-admin/coverage/lcov.info,catchbweb/coverage/lcov.info,sweep/coverage/lcov.info
sonar.python.coverage.reportPaths=sweepseries/coverage.xml
