import {
  createAcademy,
  getAcademies,
  getAcademyDetail,
  getMyAcademies,
  getFacilityOptions,
  updateAcademyIntroduction,
  updateFacilities,
  updateBusinessHours,
} from "./academy";
import {
  createCoach,
  getCoaches,
  getCoachDetails,
  getEmployedCoaches,
  acceptCoach,
  rejectCoach,
  getMyCoachProfile,
  updateCoachIntro,
  updateCoachSNS,
} from "./coach";

export {
  createAcademy,
  getAcademies,
  getAcademyDetail,
  getMyAcademies,
  getFacilityOptions,
  updateAcademyIntroduction,
  updateFacilities,
  updateBusinessHours,
  createCoach,
  getCoaches,
  getCoachDetails,
  getEmployedCoaches,
  acceptCoach,
  rejectCoach,
  getMyCoachProfile,
  updateCoachIntro,
  updateCoachSNS,
};
