import {
  createAcademy,
  getAcademies,
  getAcademyDetail,
  getMyAcademies,
  getFacilityOptions,
  updateAcademyIntroduction,
  updateFacilities,
  updateBusinessHours,
  updateLogo,
  uploadImage,
  deleteImage,
} from "./academy";
import {
  createCoach,
  getCoaches,
  getCoachDetails,
  getEmployedCoaches,
  acceptCoach,
  rejectCoach,
  getMyCoachProfile,
  updateCoachIntro,
  updateCoachSNS,
} from "./coach";
import { createNotice, getNotices, getNotice, deleteNotice, editNotice } from "./notices";
import { getTargets, getPositions, createProgram, getPrograms } from "./programs";

export {
  createAcademy,
  getAcademies,
  getAcademyDetail,
  getMyAcademies,
  getFacilityOptions,
  updateAcademyIntroduction,
  updateFacilities,
  updateBusinessHours,
  updateLogo,
  uploadImage,
  deleteImage,
  createCoach,
  getCoaches,
  getCoachDetails,
  getEmployedCoaches,
  acceptCoach,
  rejectCoach,
  getMyCoachProfile,
  updateCoachIntro,
  updateCoachSNS,
  createNotice,
  getNotices,
  getNotice,
  deleteNotice,
  editNotice,
  getTargets,
  getPositions,
  getPrograms,
  createProgram,
};
