# Generated by Django 4.2.16 on 2024-11-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum', models.IntegerField(choices=[(1, '덕아웃'), (2, '드래프트'), (3, '장터'), (4, '스틸')])),
                ('name', models.CharField(max_length=20)),
                ('icon', models.URLField()),
                ('color', models.CharField(max_length=7)),
                ('bgcolor', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['name'],
            },
        ),
    ]
