# Generated by Django 4.2.16 on 2024-11-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'verbose_name': '게시글 태그', 'verbose_name_plural': '게시글 태그'},
        ),
    ]
