# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
    ]
