# Generated by Django 4.2.16 on 2025-01-26 18:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diary',
            unique_together={('user', 'date')},
        ),
    ]
