# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['date'], 'verbose_name': '다이어리', 'verbose_name_plural': '다이어리'},
        ),
    ]
