# Generated by Django 4.2.16 on 2025-02-24 05:48

import auth.userprofile.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=auth.userprofile.utils.random_nickname_generator, max_length=150)),
                ('profile_image', models.URLField(null=True)),
                ('default_color', models.CharField(default=auth.userprofile.utils.random_color_generator, max_length=7)),
                ('introduction', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'indexes': [models.Index(fields=['user'], name='user_profil_user_id_4f95f8_idx')],
            },
        ),
    ]
