# Generated by Django 4.2.16 on 2024-11-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='introduction',
            field=models.CharField(default='', max_length=300),
        ),
    ]
