# Generated by Django 4.2.16 on 2025-02-24 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('person', '0001_initial'),
        ('program', '0001_initial'),
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coaches', models.ManyToManyField(related_name='lessons', to='coach.coach')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='program.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='person.person')),
            ],
            options={
                'db_table': 'lessons',
                'unique_together': {('program', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('notify', models.BooleanField(default=False)),
                ('notify_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('coaches', models.ManyToManyField(related_name='sessions', to='coach.coach')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='contract.contract')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='lesson.lesson')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
    ]
