# Generated by Django 4.2.16 on 2025-03-10 02:00

from django.db import migrations, models
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_datetime',
            field=models.DateTimeField(validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(validators=[product.validators.validate_30_minutes_interval]),
        ),
    ]
