# Generated by Django 4.2.16 on 2025-03-10 02:38

from django.db import migrations, models
import django.db.models.deletion
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
        ('coach', '0003_alter_coachworkinghours_end_time_and_more'),
        ('lesson', '0002_alter_session_end_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(validators=[product.validators.validate_30_minutes_interval])),
                ('end_datetime', models.DateTimeField(validators=[product.validators.validate_30_minutes_interval])),
                ('notify', models.BooleanField(default=False)),
                ('notify_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('coaches', models.ManyToManyField(related_name='requests', to='coach.coach')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='contract.contract')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='lesson.lesson')),
            ],
            options={
                'db_table': 'session_requests',
            },
        ),
    ]
