# Generated by Django 4.2.16 on 2025-03-10 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_sessionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
