# Generated by Django 4.2.16 on 2025-03-10 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_sessionrequest_created_at_sessionrequest_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionrequest',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='notify',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='notify_time',
        ),
    ]
