# Generated by Django 4.2.16 on 2025-03-10 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_alter_program_select_disabled'),
        ('lesson', '0005_remove_sessionrequest_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='program.curriculum'),
            preserve_default=False,
        ),
    ]
