# Generated by Django 4.2.16 on 2025-03-10 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('program', '0007_alter_program_select_disabled'),
        ('lesson', '0006_sessionrequest_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionrequest',
            name='lesson',
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='program.program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='person.person'),
            preserve_default=False,
        ),
    ]
