# Generated by Django 4.2.16 on 2025-03-10 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_remove_sessionrequest_lesson_sessionrequest_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionrequest',
            name='end_datetime',
        ),
    ]
