# Generated by Django 4.2.16 on 2025-03-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_alter_coachworkinghours_end_time_and_more'),
        ('lesson', '0008_remove_sessionrequest_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrequest',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='requests', to='coach.coach'),
        ),
    ]
