# Generated by Django 4.2.16 on 2025-03-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_alter_sessionrequest_coaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
