# Generated by Django 4.2.16 on 2025-04-02 02:21

from django.db import migrations, models
import django.db.models.deletion
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_sessionrequest_accepted_sessionrequest_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_start_datetime', models.DateTimeField(validators=[product.validators.validate_30_minutes_interval])),
                ('new_end_datetime', models.DateTimeField(validators=[product.validators.validate_30_minutes_interval])),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_requests', to='lesson.session')),
            ],
            options={
                'db_table': 'schedule_change_requests',
            },
        ),
    ]
