# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0011_schedulechangerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '레슨', 'verbose_name_plural': '레슨'},
        ),
        migrations.AlterModelOptions(
            name='schedulechangerequest',
            options={'verbose_name': '레슨 일정 변경 요청', 'verbose_name_plural': '레슨 일정 변경 요청'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': '레슨 세션', 'verbose_name_plural': '레슨 세션'},
        ),
        migrations.AlterModelOptions(
            name='sessionrequest',
            options={'verbose_name': '레슨 요청', 'verbose_name_plural': '레슨 요청'},
        ),
    ]
