# Generated by Django 4.2.16 on 2024-11-25 21:16

import community.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0004_alter_userprofile_options_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0003_alter_tag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', community.models.CustomAutoField(primary_key=True, serialize=False)),
                ('forum', models.IntegerField(choices=[(1, '덕아웃'), (2, '드래프트'), (3, '장터'), (4, '스틸')])),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('num_views', models.IntegerField(default=0)),
                ('is_under_review', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
                ('images', models.ManyToManyField(blank=True, to='post.image')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tag.tag')),
            ],
            options={
                'db_table': 'post',
                'ordering': ['-created_at'],
                'unique_together': {('forum', 'author', 'title')},
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_content', models.TextField()),
                ('report_reason', models.CharField(choices=[('IN', '욕설/비방'), ('VI', '폭력/협박/위협'), ('PO', '음란물'), ('UN', '거짓/허위정보'), ('AD', '도배/스팸/광고'), ('PI', '개인정보 침해'), ('PL', '정치적인 내용'), ('WC', '잘못된 게시판/태그'), ('OT', '기타')], default='OT', max_length=2)),
                ('review_status', models.IntegerField(choices=[(0, '제출됨'), (1, '검토중'), (2, '검토 완료')], default=0)),
                ('report_status', models.IntegerField(choices=[(0, '대기중'), (1, '수락됨'), (2, '거부됨'), (3, '일부 수락됨')], default=0)),
                ('feedback', models.TextField(blank=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reports', to='post.post')),
                ('report_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_report',
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='userprofile.userprofile')),
            ],
            options={
                'db_table': 'post_like',
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PostContentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_first_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_last_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
            ],
            options={
                'db_table': 'content_view',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
