# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '게시물 이미지', 'verbose_name_plural': '게시물 이미지'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': '게시물', 'verbose_name_plural': '게시물'},
        ),
        migrations.AlterModelOptions(
            name='postcontentview',
            options={'verbose_name': '게시물 조회', 'verbose_name_plural': '게시물 조회'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': '게시물 좋아요', 'verbose_name_plural': '게시물 좋아요'},
        ),
        migrations.AlterModelOptions(
            name='postreport',
            options={'verbose_name': '게시물 신고', 'verbose_name_plural': '게시물 신고'},
        ),
    ]
