# Generated by Django 4.2.16 on 2024-11-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='forum',
            field=models.IntegerField(choices=[(1, '덕아웃'), (2, '드래프트'), (3, '마켓'), (4, '스틸')]),
        ),
    ]
