# Generated by Django 4.2.16 on 2024-11-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postlike_user_alter_postreport_report_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='post_image',
        ),
        migrations.AlterModelTable(
            name='postcontentview',
            table='post_content_view',
        ),
    ]
