# Generated by Django 4.2.16 on 2024-11-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_image_table_alter_postcontentview_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreport',
            name='review_status',
        ),
        migrations.AlterField(
            model_name='postreport',
            name='report_status',
            field=models.IntegerField(choices=[(0, '제출됨'), (1, '검토중'), (2, '검토 완료')], default=0),
        ),
    ]
