# Generated by Django 4.2.16 on 2024-11-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_postreport_review_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='report_status',
            field=models.IntegerField(choices=[(0, '검토중'), (1, '처리완료'), (2, '처리완료 (반려)')], default=0),
        ),
    ]
