# Generated by Django 4.2.16 on 2024-12-19 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('color', models.CharField(max_length=7)),
                ('is_allday', models.BooleanField(default=False)),
                ('notify', models.BooleanField(default=False)),
                ('repeat', models.BooleanField(default=False)),
                ('repeat_type', models.CharField(blank=True, max_length=1, null=True)),
                ('repeat_until', models.DateTimeField(blank=True, null=True)),
                ('repeat_every', models.IntegerField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='calendarapp.calendar')),
            ],
        ),
    ]
