# Generated by Django 4.2.16 on 2025-02-24 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=7)),
                ('repeat_type', models.CharField(choices=[('N', '반복 없음'), ('D', '매일'), ('W', '매주'), ('M', '매월'), ('Y', '매년')], default='N', max_length=1)),
                ('repeat_until', models.DateTimeField(blank=True, null=True)),
                ('repeat_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_allday', models.BooleanField(default=False)),
                ('notify', models.BooleanField(default=False)),
                ('notify_time', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_events', to='schedule.personalschedule')),
            ],
            options={
                'db_table': 'personal_events',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AcademySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=7)),
                ('repeat_type', models.CharField(choices=[('N', '반복 없음'), ('D', '매일'), ('W', '매주'), ('M', '매월'), ('Y', '매년')], default='N', max_length=1)),
                ('repeat_until', models.DateTimeField(blank=True, null=True)),
                ('repeat_count', models.IntegerField(default=0)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_schedules', to='academy.academy')),
            ],
            options={
                'db_table': 'academy_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_allday', models.BooleanField(default=False)),
                ('notify', models.BooleanField(default=False)),
                ('notify_time', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_events', to='schedule.academyschedule')),
            ],
            options={
                'db_table': 'academy_events',
                'ordering': ['start_datetime'],
            },
        ),
    ]
