# Generated by Django 4.2.16 on 2025-01-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start_datetime']},
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedules',
        ),
    ]
