# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academyevent',
            options={'ordering': ['start_datetime'], 'verbose_name': '아카데미 일정 상세', 'verbose_name_plural': '아카데미 일정 상세'},
        ),
        migrations.AlterModelOptions(
            name='academyschedule',
            options={'ordering': ['-created_at'], 'verbose_name': '아카데미 일정', 'verbose_name_plural': '아카데미 일정'},
        ),
        migrations.AlterModelOptions(
            name='personalevent',
            options={'ordering': ['start_datetime'], 'verbose_name': '개인 일정 상세', 'verbose_name_plural': '개인 일정 상세'},
        ),
        migrations.AlterModelOptions(
            name='personalschedule',
            options={'ordering': ['-created_at'], 'verbose_name': '개인 일정', 'verbose_name_plural': '개인 일정'},
        ),
        migrations.AlterField(
            model_name='academyschedule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personalschedule',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
