# Generated by Django 4.2.16 on 2025-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_options_alter_schedule_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='repeat_every',
        ),
        migrations.AddField(
            model_name='schedule',
            name='repeat_count',
            field=models.IntegerField(default=0),
        ),
    ]
