# Generated by Django 4.2.16 on 2025-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_schedule_repeat_every_schedule_repeat_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='repeat',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='repeat_type',
            field=models.CharField(choices=[('N', '반복 없음'), ('D', '매일'), ('W', '매주'), ('M', '매월'), ('Y', '매년')], default='N', max_length=1),
        ),
    ]
