# Generated by Django 4.2.16 on 2025-01-20 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_schedule_repeat_alter_schedule_repeat_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_allday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_allday', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedule.schedule')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['start_datetime'],
            },
        ),
    ]
