# Generated by Django 4.2.16 on 2025-01-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_schedule_options_remove_schedule_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='notify_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
