# Generated by Django 4.2.16 on 2025-01-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_schedule_notify_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='notify',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='notify_time',
        ),
        migrations.AddField(
            model_name='event',
            name='notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='notify_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
