# Generated by Django 4.2.16 on 2025-02-05 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_person_gender'),
        ('program', '0002_curriculum'),
        ('coach', '0006_alter_coach_blog_alter_coach_instagram'),
        ('schedule', '0007_remove_schedule_notify_remove_schedule_notify_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('coaches', models.ManyToManyField(related_name='lessons', to='coach.coach')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='program.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='person.person')),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('notify', models.BooleanField(default=False)),
                ('notify_time', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='schedule.lesson')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
    ]
