# Generated by Django 4.2.16 on 2025-02-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_lesson_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
