# Generated by Django 4.2.16 on 2025-02-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_session_feedback_session_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='notes',
        ),
        migrations.AlterField(
            model_name='session',
            name='feedback',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
