# Generated by Django 4.2.16 on 2025-02-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_person_gender'),
        ('program', '0002_curriculum'),
        ('schedule', '0010_remove_lesson_notes_alter_session_feedback_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('program', 'student')},
        ),
    ]
