# Generated by Django 4.2.16 on 2025-02-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_alter_coach_blog_alter_coach_instagram'),
        ('schedule', '0011_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='coaches',
            field=models.ManyToManyField(related_name='sessions', to='coach.coach'),
        ),
    ]
