# Generated by Django 4.2.16 on 2025-02-19 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contract_options_contract_created_at_and_more'),
        ('schedule', '0012_session_coaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='contract.contract'),
            preserve_default=False,
        ),
    ]
