# Generated by Django 4.2.16 on 2024-12-08 02:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('kor_name', models.CharField(max_length=50, unique=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '편의시설'), (2, '장비'), (3, '기타')])),
            ],
            options={
                'db_table': 'academy_facility',
            },
        ),
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academy_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('registration_number', models.CharField(max_length=12, unique=True)),
                ('certificate', models.ImageField(upload_to='academy/registration/certificate/')),
                ('logo', models.ImageField(upload_to='academy/logo/')),
                ('introduction', models.TextField()),
                ('homepage', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('blog', models.URLField(blank=True)),
                ('num_mounds', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('num_plates', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_verified', models.BooleanField(default=False)),
                ('convenience', models.ManyToManyField(blank=True, related_name='academies', to='academy.academyfacility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
