# Generated by Django 4.2.16 on 2025-02-24 05:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('academy_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('registration_number', models.CharField(max_length=12, unique=True)),
                ('certificate', models.FileField(upload_to='')),
                ('logo', models.ImageField(upload_to='')),
                ('introduction', models.TextField()),
                ('homepage', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('blog', models.URLField(blank=True)),
                ('num_mounds', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('num_plates', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('reject_reason', models.TextField(blank=True)),
                ('notifications', models.BooleanField(default=True)),
                ('notifications_today', models.BooleanField(default=True)),
                ('daily_time', models.TimeField(blank=True, default='09:00:00', null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academy', to='address.address')),
            ],
            options={
                'db_table': 'academy',
            },
        ),
        migrations.CreateModel(
            name='AcademyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('kor_name', models.CharField(max_length=50, unique=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '편의시설'), (2, '구비장비'), (3, '기타')])),
            ],
            options={
                'db_table': 'academy_facility',
            },
        ),
        migrations.CreateModel(
            name='AcademyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '공지'), (2, '이벤트'), (3, '기타')], default=1)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='academy.academy')),
            ],
            options={
                'db_table': 'academy_notice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='academy.academy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_review',
            },
        ),
        migrations.CreateModel(
            name='AcademyNoticeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='academy.academynotice')),
            ],
            options={
                'db_table': 'academy_notice_attachment',
            },
        ),
        migrations.CreateModel(
            name='AcademyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='academy.academy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_academies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_like',
            },
        ),
        migrations.CreateModel(
            name='AcademyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.academy')),
            ],
            options={
                'db_table': 'academy_image',
            },
        ),
        migrations.AddField(
            model_name='academy',
            name='convenience',
            field=models.ManyToManyField(blank=True, related_name='academies', to='academy.academyfacility'),
        ),
        migrations.AddField(
            model_name='academy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField(default='09:00:00')),
                ('close_time', models.TimeField(default='21:00:00')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')])),
                ('is_closed', models.BooleanField(default=False)),
                ('is_allday', models.BooleanField(default=False)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='academy.academy')),
            ],
            options={
                'db_table': 'business_hours',
                'unique_together': {('academy', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='AcademyStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('notifications', models.BooleanField(default=True)),
                ('notifications_today', models.BooleanField(default=True)),
                ('daily_time', models.TimeField(blank=True, default='09:00:00', null=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academy.academy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academies', to='person.person')),
            ],
            options={
                'db_table': 'academy_student',
                'unique_together': {('academy', 'student')},
            },
        ),
    ]
