# Generated by Django 4.2.16 on 2025-02-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='calendar_scope',
            field=models.PositiveSmallIntegerField(choices=[(1, '전체 공개'), (2, '부분 공개'), (3, '비공개')], default=1),
        ),
    ]
