# Generated by Django 4.2.16 on 2024-12-09 15:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='academy', to='address.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academy',
            name='name',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academy',
            name='certificate',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='academy',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterModelTable(
            name='academy',
            table='academy',
        ),
        migrations.CreateModel(
            name='AcademyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='academy.academy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_review',
            },
        ),
        migrations.CreateModel(
            name='AcademyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='academy.academy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_academies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_like',
            },
        ),
    ]
