# Generated by Django 4.2.16 on 2025-03-19 11:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academystudent',
            old_name='student',
            new_name='person',
        ),
        migrations.AlterUniqueTogether(
            name='academystudent',
            unique_together={('academy', 'person')},
        ),
        migrations.AddField(
            model_name='academy',
            name='calendar_scope',
            field=models.PositiveSmallIntegerField(choices=[(1, '전체 공개'), (2, '부분 공개'), (3, '비공개')], default=1),
        ),
        migrations.AlterField(
            model_name='academy',
            name='daily_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='academystudent',
            name='daily_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='close_time',
            field=models.TimeField(default=datetime.time(21, 0), validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='open_time',
            field=models.TimeField(default=datetime.time(9, 0), validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=50)),
                ('start_time', models.TimeField(default=datetime.time(9, 0), validators=[product.validators.validate_30_minutes_interval])),
                ('end_time', models.TimeField(default=datetime.time(21, 0), validators=[product.validators.validate_30_minutes_interval])),
                ('is_closed', models.BooleanField(default=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_days', to='academy.academy')),
            ],
            options={
                'db_table': 'special_day',
                'unique_together': {('academy', 'date')},
            },
        ),
    ]
