# Generated by Django 4.2.16 on 2024-12-10 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('academy', '0002_academy_address_academy_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academy',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academy', to='address.address'),
        ),
    ]
