# Generated by Django 4.2.16 on 2025-02-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('academy', '0002_academy_calendar_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academystudent',
            old_name='student',
            new_name='person',
        ),
        migrations.AlterUniqueTogether(
            name='academystudent',
            unique_together={('academy', 'person')},
        ),
    ]
