# Generated by Django 4.2.16 on 2025-03-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_rename_student_academystudent_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='cached_rating',
            field=models.FloatField(default=0),
        ),
    ]
