# Generated by Django 4.2.16 on 2024-12-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_academy_is_rejected_alter_academy_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='verified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
