# Generated by Django 4.2.16 on 2025-03-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_academy_cached_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademyReview',
        ),
    ]
