# Generated by Django 4.2.16 on 2025-03-10 01:14

from django.db import migrations, models
import django.db.models.deletion
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_rename_student_academystudent_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='close_time',
            field=models.TimeField(default='21:00:00', validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='open_time',
            field=models.TimeField(default='09:00:00', validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=50)),
                ('start_time', models.TimeField(default='09:00:00', validators=[product.validators.validate_30_minutes_interval])),
                ('end_time', models.TimeField(default='21:00:00', validators=[product.validators.validate_30_minutes_interval])),
                ('is_closed', models.BooleanField(default=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_days', to='academy.academy')),
            ],
            options={
                'db_table': 'special_day',
                'unique_together': {('academy', 'date')},
            },
        ),
    ]
