# Generated by Django 4.2.16 on 2025-03-11 01:36

import datetime
from django.db import migrations, models
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_businesshours_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='daily_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='academystudent',
            name='daily_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='close_time',
            field=models.TimeField(default=datetime.time(21, 0), validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='open_time',
            field=models.TimeField(default=datetime.time(9, 0), validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='end_time',
            field=models.TimeField(default=datetime.time(21, 0), validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0), validators=[product.validators.validate_30_minutes_interval]),
        ),
    ]
