# Generated by Django 4.2.16 on 2025-03-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_delete_academyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
