# Generated by Django 4.2.16 on 2024-12-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_academy_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
    ]
