# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_academy_num_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academy',
            options={'verbose_name': '아카데미', 'verbose_name_plural': '아카데미'},
        ),
        migrations.AlterModelOptions(
            name='academyfacility',
            options={'verbose_name': '아카데미 시설', 'verbose_name_plural': '아카데미 시설'},
        ),
        migrations.AlterModelOptions(
            name='academyimage',
            options={'verbose_name': '아카데미 이미지', 'verbose_name_plural': '아카데미 이미지'},
        ),
        migrations.AlterModelOptions(
            name='academylike',
            options={'verbose_name': '아카데미 좋아요', 'verbose_name_plural': '아카데미 좋아요'},
        ),
        migrations.AlterModelOptions(
            name='academynotice',
            options={'ordering': ['-created_at'], 'verbose_name': '아카데미 공지사항', 'verbose_name_plural': '아카데미 공지사항'},
        ),
        migrations.AlterModelOptions(
            name='academynoticeattachment',
            options={'verbose_name': '아카데미 공지사항 첨부파일', 'verbose_name_plural': '아카데미 공지사항 첨부파일'},
        ),
        migrations.AlterModelOptions(
            name='academystudent',
            options={'verbose_name': '아카데미 학생', 'verbose_name_plural': '아카데미 학생'},
        ),
        migrations.AlterModelOptions(
            name='businesshours',
            options={'verbose_name': '아카데미 운영시간', 'verbose_name_plural': '아카데미 운영시간'},
        ),
        migrations.AlterModelOptions(
            name='specialday',
            options={'verbose_name': '아카데미 특별 일정', 'verbose_name_plural': '아카데미 특별 일정'},
        ),
    ]
