# Generated by Django 4.2.16 on 2024-12-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_academy_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academyfacility',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '편의시설'), (2, '구비장비'), (3, '기타')]),
        ),
    ]
