# Generated by Django 4.2.16 on 2024-12-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_alter_academyfacility_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField(default='09:00:00')),
                ('close_time', models.TimeField(default='21:00:00')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')])),
                ('is_closed', models.BooleanField(default=False)),
                ('is_allday', models.BooleanField(default=False)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='academy.academy')),
            ],
            options={
                'db_table': 'business_hours',
                'unique_together': {('academy', 'day_of_week')},
            },
        ),
    ]
