# Generated by Django 4.2.16 on 2024-12-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_businesshours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academyreview',
            name='title',
        ),
    ]
