# Generated by Django 4.2.16 on 2024-12-14 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_remove_academyreview_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='academy.academy')),
            ],
            options={
                'db_table': 'academy_notice',
            },
        ),
    ]
