# Generated by Django 4.2.16 on 2024-12-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_academynotice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academynotice',
            options={'ordering': ['-created_at']},
        ),
    ]
