# Generated by Django 4.2.16 on 2025-02-01 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_alter_academynotice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='academynotice',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '공지'), (2, '이벤트'), (3, '기타')], default=1),
        ),
        migrations.CreateModel(
            name='AcademyNoticeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='academy.academynotice')),
            ],
            options={
                'db_table': 'academy_notice_attachment',
            },
        ),
    ]
