# Generated by Django 4.2.16 on 2025-02-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_academynotice_type_academynoticeattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.academy')),
            ],
            options={
                'db_table': 'academy_image',
            },
        ),
    ]
