# Generated by Django 4.2.16 on 2025-02-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_person_gender'),
        ('academy', '0012_academyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='academies', to='person.person'),
        ),
    ]
