# Generated by Django 4.2.16 on 2024-12-18 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'calendar',
            },
        ),
        migrations.CreateModel(
            name='CalendarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#FF6B6B', max_length=7)),
                ('auth', models.IntegerField(choices=[(1, '소유자'), (2, '편집자'), (3, '뷰어')], default=3)),
                ('display_name', models.CharField(max_length=200)),
                ('notifications', models.BooleanField(default=True)),
                ('notifications_today', models.BooleanField(default=True)),
                ('daily_time', models.TimeField(blank=True, default='09:00:00', null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_users', to='calendarapp.calendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_user',
                'unique_together': {('user', 'calendar')},
            },
        ),
    ]
