# Generated by Django 4.2.16 on 2024-12-16 14:04

import auth.userprofile.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='color',
            field=models.CharField(default=auth.userprofile.utils.random_color_generator, max_length=7),
        ),
    ]
