# Generated by Django 4.2.16 on 2024-12-16 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0002_alter_calendar_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='color',
        ),
        migrations.CreateModel(
            name='CalendarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('#FF6B6B', '빨강'), ('#FFA07A', '주황'), ('#98FB98', '초록'), ('#B0E0E6', '청록'), ('#FFD700', '노랑'), ('#E6E6FA', '보라'), ('#87CEEB', '파랑'), ('#D8BFD8', '보라')], default='#FF6B6B', max_length=7)),
                ('display_name', models.CharField(max_length=200)),
                ('notifications', models.BooleanField(default=True)),
                ('notifications_today', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_user',
            },
        ),
        migrations.AlterField(
            model_name='calendar',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editors', to='calendarapp.calendaruser'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='calendarapp.calendaruser'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewers', to='calendarapp.calendaruser'),
        ),
    ]
