# Generated by Django 4.2.16 on 2024-12-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_remove_calendar_color_calendaruser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='viewers',
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_users', to='calendarapp.calendar'),
            preserve_default=False,
        ),
    ]
