# Generated by Django 4.2.16 on 2024-12-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_remove_calendar_editors_remove_calendar_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaruser',
            name='auth',
            field=models.IntegerField(choices=[(1, '소유자'), (2, '편집자'), (3, '뷰어')], default=3),
        ),
    ]
