# Generated by Django 4.2.16 on 2024-12-16 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0005_calendaruser_auth'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendaruser',
            unique_together={('user', 'calendar')},
        ),
    ]
