# Generated by Django 4.2.16 on 2024-12-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_alter_calendaruser_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaruser',
            name='color',
            field=models.CharField(choices=[('#FF6B6B', 'Red'), ('#FFA07A', 'Orange'), ('#98FB98', 'Green'), ('#B0E0E6', 'Cyan'), ('#FFD700', 'Yellow'), ('#E6E6FA', 'Lavender'), ('#87CEEB', 'Blue'), ('#D8BFD8', 'Purple')], default='#FF6B6B', max_length=7),
        ),
    ]
