# Generated by Django 4.2.16 on 2024-12-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_alter_calendaruser_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaruser',
            name='color',
            field=models.CharField(choices=[('#FF6B6B', '#FF6B6B'), ('#FFA07A', '#FFA07A'), ('#98FB98', '#98FB98'), ('#B0E0E6', '#B0E0E6'), ('#FFD700', '#FFD700'), ('#E6E6FA', '#E6E6FA'), ('#87CEEB', '#87CEEB'), ('#D8BFD8', '#D8BFD8')], default='#FF6B6B', max_length=7),
        ),
    ]
