# Generated by Django 4.2.16 on 2024-12-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_alter_calendaruser_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaruser',
            name='color',
            field=models.CharField(default='#FF6B6B', max_length=7),
        ),
    ]
