# Generated by Django 4.2.16 on 2024-12-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_alter_calendaruser_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaruser',
            name='daily_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
