# Generated by Django 4.2.16 on 2024-12-17 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_calendaruser_daily_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaruser',
            name='daily_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
    ]
