# Generated by Django 4.2.16 on 2024-12-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0011_alter_calendaruser_daily_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaruser',
            name='daily_time',
            field=models.TimeField(blank=True, default='09:00:00', null=True),
        ),
    ]
