# Generated by Django 4.2.16 on 2025-02-24 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'program_position',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'program_target',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academy.academy')),
                ('coaches', models.ManyToManyField(related_name='programs', to='coach.coach')),
                ('positions', models.ManyToManyField(related_name='programs', to='program.position')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='program.target')),
            ],
            options={
                'db_table': 'program',
                'unique_together': {('academy', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lessons', models.PositiveSmallIntegerField()),
                ('price', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='program.program')),
            ],
            options={
                'db_table': 'program_curriculum',
                'unique_together': {('program', 'num_lessons')},
            },
        ),
    ]
