# Generated by Django 4.2.16 on 2024-12-15 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0010_alter_academynotice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'program_position',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'program_target',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academy.academy')),
                ('positions', models.ManyToManyField(related_name='programs', to='program.position')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='program.target')),
            ],
            options={
                'db_table': 'program',
                'unique_together': {('academy', 'name')},
            },
        ),
    ]
