# Generated by Django 4.2.16 on 2025-02-26 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='coaches',
        ),
        migrations.CreateModel(
            name='CoachTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coaches', models.ManyToManyField(related_name='coach_teams', to='coach.coach')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_teams', to='program.program')),
            ],
        ),
    ]
