# Generated by Django 4.2.16 on 2024-12-15 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lessons', models.PositiveSmallIntegerField()),
                ('price', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='program.program')),
            ],
            options={
                'db_table': 'program_curriculum',
                'unique_together': {('program', 'num_lessons')},
            },
        ),
    ]
