# Generated by Django 4.2.16 on 2025-02-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_alter_coach_blog_alter_coach_instagram'),
        ('program', '0002_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='coaches',
            field=models.ManyToManyField(related_name='programs', to='coach.coach'),
        ),
    ]
