# Generated by Django 4.2.16 on 2025-02-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_remove_program_coaches_coachteam'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coachteam',
            table='program_coach_team',
        ),
    ]
