# Generated by Django 4.2.16 on 2025-02-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_alter_coachteam_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachteam',
            name='program',
        ),
        migrations.AddField(
            model_name='program',
            name='teams',
            field=models.ManyToManyField(related_name='programs', to='program.coachteam'),
        ),
    ]
