# Generated by Django 4.2.16 on 2025-02-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_remove_coachteam_program_program_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
