# Generated by Django 4.2.16 on 2025-02-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_curriculum_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='select_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
