# Generated by Django 4.2.16 on 2025-02-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_program_select_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='select_disabled',
            field=models.BooleanField(default=True),
        ),
    ]
