# Generated by Django 4.2.16 on 2025-03-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_alter_program_select_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cached_rating',
            field=models.FloatField(default=0),
        ),
    ]
