# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_program_num_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachteam',
            options={'verbose_name': '코치 팀', 'verbose_name_plural': '코치 팀'},
        ),
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name': '프로그램 커리큘럼', 'verbose_name_plural': '프로그램 커리큘럼'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': '프로그램 포지션 옵션', 'verbose_name_plural': '프로그램 포지션 옵션'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': '프로그램', 'verbose_name_plural': '프로그램'},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': '프로그램 대상', 'verbose_name_plural': '프로그램 대상'},
        ),
    ]
