# Generated by Django 4.2.16 on 2024-11-14 16:17

import auth.person.utils
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('nickname', models.CharField(default=auth.person.utils.random_nickname_generator, max_length=150)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('U', '미입력'), ('M', '남성'), ('F', '여성')], default='U', max_length=1)),
                ('profile_image', models.ImageField(null=True, upload_to='')),
                ('default_color', models.CharField(default=auth.person.utils.random_color_generator, max_length=7)),
            ],
            options={
                'db_table': 'person',
                'indexes': [models.Index(fields=['phone_number'], name='person_phone_n_592235_idx')],
            },
        ),
    ]
