# Generated by Django 4.2.16 on 2025-02-24 05:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('U', '미입력'), ('M', '남성'), ('F', '여성'), ('O', '기타')], default='U', max_length=1)),
            ],
            options={
                'verbose_name': '사람',
                'verbose_name_plural': '사람들',
                'db_table': 'person',
                'indexes': [models.Index(fields=['phone_number'], name='person_phone_n_592235_idx')],
            },
        ),
    ]
