# Generated by Django 4.2.16 on 2024-11-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '야구인', 'verbose_name_plural': '야구인'},
        ),
    ]
