# Generated by Django 4.2.16 on 2024-11-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='default_color',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='profile_image',
        ),
    ]
