# Generated by Django 4.2.16 on 2024-11-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_person_default_color_remove_person_nickname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
    ]
