# Generated by Django 4.2.16 on 2024-11-28 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '사람', 'verbose_name_plural': '사람들'},
        ),
    ]
