# Generated by Django 4.2.16 on 2024-12-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_person_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
