# Generated by Django 4.2.16 on 2025-01-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_rename_first_name_person_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('U', '미입력'), ('M', '남성'), ('F', '여성'), ('O', '기타')], default='U', max_length=1),
        ),
    ]
