# Generated by Django 4.2.16 on 2024-12-08 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sido',
            fields=[
                ('sido_code', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('sido_name', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=2)),
                ('display', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'sido',
            },
        ),
        migrations.CreateModel(
            name='Sigungu',
            fields=[
                ('sigungu_code', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('sigungu_name', models.CharField(max_length=20)),
                ('sido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.sido')),
            ],
            options={
                'db_table': 'sigungu',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_address_part1', models.CharField(max_length=30)),
                ('road_address_part2', models.CharField(max_length=30)),
                ('building_name', models.CharField(max_length=30)),
                ('eng_address', models.CharField(max_length=80)),
                ('jibun_address', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=5)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('map_image', models.ImageField(blank=True, upload_to='')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.sigungu')),
            ],
            options={
                'db_table': 'address',
                'unique_together': {('road_address_part1', 'road_address_part2')},
            },
        ),
    ]
