# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '주소', 'verbose_name_plural': '주소'},
        ),
        migrations.AlterModelOptions(
            name='sido',
            options={'verbose_name': '시도', 'verbose_name_plural': '시도'},
        ),
        migrations.AlterModelOptions(
            name='sigungu',
            options={'verbose_name': '시군구', 'verbose_name_plural': '시군구'},
        ),
    ]
