# Generated by Django 4.2.16 on 2024-11-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '회원', 'verbose_name_plural': '회원'},
        ),
    ]
