# Generated by Django 4.2.16 on 2025-01-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_kakao_linked_user_naver_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='noti_permitted',
            field=models.BooleanField(default=False),
        ),
    ]
