# Generated by Django 4.2.16 on 2025-01-27 19:14

import auth.user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_agreed_at_user_noti_permitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('verification_code', models.CharField(default=auth.user.utils.generate_verification_code, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '휴대폰 인증',
                'verbose_name_plural': '휴대폰 인증',
                'db_table': 'phone_verification',
            },
        ),
    ]
