# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': '문의', 'verbose_name_plural': '문의'},
        ),
    ]
