# Generated by Django 4.2.16 on 2025-02-24 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('introduction', models.TextField()),
                ('certificate', models.FileField(upload_to='')),
                ('profile_image', models.ImageField(upload_to='')),
                ('career', models.IntegerField(choices=[(0, '미지정'), (1, '프로선수 출신'), (2, '대학선수 출신'), (3, '고교선수 출신'), (4, '독립리그 출신'), (5, '해외대학 출신'), (6, '트레이닝 코치')], default=0)),
                ('instagram', models.URLField(blank=True)),
                ('blog', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('reject_reason', models.TextField(blank=True)),
                ('status', models.SmallIntegerField(choices=[(0, '대기중'), (1, '승인됨'), (2, '거절됨')], default=0)),
                ('notifications', models.BooleanField(default=True)),
                ('notifications_today', models.BooleanField(default=True)),
                ('daily_time', models.TimeField(blank=True, default='09:00:00', null=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='academy.academy')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='person.person')),
            ],
            options={
                'db_table': 'coach',
            },
        ),
        migrations.CreateModel(
            name='CoachProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=20, unique=True)),
                ('kor_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'coach_profession',
            },
        ),
        migrations.CreateModel(
            name='CoachReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='coach.coach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coach_review',
            },
        ),
        migrations.CreateModel(
            name='CoachLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='coach.coach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_coaches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coach_like',
            },
        ),
        migrations.AddField(
            model_name='coach',
            name='professions',
            field=models.ManyToManyField(related_name='coaches', to='coach.coachprofession'),
        ),
    ]
