# Generated by Django 4.2.16 on 2024-12-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=20, unique=True)),
                ('kor_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'coach_profession',
            },
        ),
        migrations.AddField(
            model_name='coach',
            name='career',
            field=models.IntegerField(choices=[(0, '미지정'), (1, '프로선수 출신'), (2, '대학선수 출신'), (3, '고교선수 출신'), (4, '독립리그 출신'), (5, '해외대학 출신'), (6, '트레이닝 코치')], default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='professions',
            field=models.ManyToManyField(related_name='coaches', to='coach.coachprofession'),
        ),
    ]
