# Generated by Django 4.2.16 on 2025-03-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=50)),
                ('start_time', models.TimeField(default='09:00:00')),
                ('end_time', models.TimeField(default='21:00:00')),
                ('is_off', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_days', to='coach.coach')),
            ],
            options={
                'db_table': 'special_working_day',
                'unique_together': {('coach', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CoachWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')])),
                ('start_time', models.TimeField(default='09:00:00')),
                ('end_time', models.TimeField(default='21:00:00')),
                ('is_off', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='coach.coach')),
            ],
            options={
                'db_table': 'coach_working_hours',
                'unique_together': {('coach', 'day_of_week')},
            },
        ),
    ]
