# Generated by Django 4.2.16 on 2025-03-10 01:14

from django.db import migrations, models
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_specialworkingday_coachworkinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachworkinghours',
            name='end_time',
            field=models.TimeField(default='21:00:00', validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.AlterField(
            model_name='coachworkinghours',
            name='start_time',
            field=models.TimeField(default='09:00:00', validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.AlterField(
            model_name='specialworkingday',
            name='end_time',
            field=models.TimeField(default='21:00:00', validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.AlterField(
            model_name='specialworkingday',
            name='start_time',
            field=models.TimeField(default='09:00:00', validators=[product.validators.validate_30_minutes_interval]),
        ),
    ]
