# Generated by Django 4.2.16 on 2024-12-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_coachprofession_coach_career_coach_professions'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='certificate',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
