# Generated by Django 4.2.16 on 2024-12-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_coach_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '대기중'), (1, '승인됨'), (2, '거절됨')], default=0),
        ),
    ]
