# Generated by Django 4.2.16 on 2025-03-11 01:36

import datetime
from django.db import migrations, models
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_alter_coachworkinghours_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='daily_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='coachworkinghours',
            name='end_time',
            field=models.TimeField(default=datetime.time(9, 0), validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.AlterField(
            model_name='coachworkinghours',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0), validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.AlterField(
            model_name='specialworkingday',
            name='end_time',
            field=models.TimeField(default=datetime.time(9, 0), validators=[product.validators.validate_30_minutes_interval]),
        ),
        migrations.AlterField(
            model_name='specialworkingday',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0), validators=[product.validators.validate_30_minutes_interval]),
        ),
    ]
