# Generated by Django 4.2.16 on 2025-03-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_alter_coach_daily_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoachReview',
        ),
    ]
