# Generated by Django 4.2.16 on 2024-12-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_coach_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='blog',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coach',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
