# Generated by Django 4.2.16 on 2025-03-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_delete_coachreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='cached_rating',
            field=models.FloatField(default=0),
        ),
    ]
