# Generated by Django 4.2.16 on 2024-12-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_coach_blog_coach_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='blog',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
