# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_coach_num_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': '코치', 'verbose_name_plural': '코치'},
        ),
        migrations.AlterModelOptions(
            name='coachlike',
            options={'verbose_name': '코치 좋아요', 'verbose_name_plural': '코치 좋아요'},
        ),
        migrations.AlterModelOptions(
            name='coachprofession',
            options={'verbose_name': '코치 전문분야', 'verbose_name_plural': '코치 전문분야'},
        ),
        migrations.AlterModelOptions(
            name='coachworkinghours',
            options={'verbose_name': '코치 근무시간', 'verbose_name_plural': '코치 근무시간'},
        ),
        migrations.AlterModelOptions(
            name='specialworkingday',
            options={'verbose_name': '코치 특별 근무일', 'verbose_name_plural': '코치 특별 근무일'},
        ),
    ]
