# Generated by Django 4.2.20 on 2025-04-08 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_alter_academy_options_alter_academyfacility_options_and_more'),
        ('person', '0001_initial'),
        ('coach', '0008_alter_coach_options_alter_coachlike_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='person.person'),
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('person', 'academy')},
        ),
    ]
