# Generated by Django 4.2.16 on 2024-11-26 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0004_alter_userprofile_options_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_alter_post_forum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='userprofile.userprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='post.post')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recomments', to='userprofile.userprofile')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recomments', to='comment.comment')),
            ],
            options={
                'db_table': 'recomment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReCommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_content', models.TextField()),
                ('report_reason', models.CharField(choices=[('IN', '욕설/비방'), ('VI', '폭력/협박/위협'), ('PO', '음란물'), ('UN', '거짓/허위정보'), ('AD', '도배/스팸/광고'), ('PI', '개인정보 침해'), ('PL', '정치적인 내용'), ('WC', '잘못된 게시판/태그'), ('OT', '기타')], default='OT', max_length=2)),
                ('review_status', models.IntegerField(choices=[(0, '제출됨'), (1, '검토중'), (2, '검토 완료')], default=0)),
                ('report_status', models.IntegerField(choices=[(0, '대기중'), (1, '수락됨'), (2, '거부됨'), (3, '일부 수락됨')], default=0)),
                ('feedback', models.TextField(blank=True)),
                ('recomment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomment_reports', to='comment.recomment')),
                ('report_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recomment_report',
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_content', models.TextField()),
                ('report_reason', models.CharField(choices=[('IN', '욕설/비방'), ('VI', '폭력/협박/위협'), ('PO', '음란물'), ('UN', '거짓/허위정보'), ('AD', '도배/스팸/광고'), ('PI', '개인정보 침해'), ('PL', '정치적인 내용'), ('WC', '잘못된 게시판/태그'), ('OT', '기타')], default='OT', max_length=2)),
                ('review_status', models.IntegerField(choices=[(0, '제출됨'), (1, '검토중'), (2, '검토 완료')], default=0)),
                ('report_status', models.IntegerField(choices=[(0, '대기중'), (1, '수락됨'), (2, '거부됨'), (3, '일부 수락됨')], default=0)),
                ('feedback', models.TextField(blank=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reports', to='comment.comment')),
                ('report_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_report',
            },
        ),
        migrations.CreateModel(
            name='ReCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('recomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomment_likes', to='comment.recomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
            ],
            options={
                'db_table': 'recomment_like',
                'unique_together': {('recomment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='comment.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
            ],
            options={
                'db_table': 'comment_like',
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
