# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': '댓글 좋아요', 'verbose_name_plural': '댓글 좋아요'},
        ),
        migrations.AlterModelOptions(
            name='commentreport',
            options={'verbose_name': '댓글 신고', 'verbose_name_plural': '댓글 신고'},
        ),
        migrations.AlterModelOptions(
            name='recomment',
            options={'ordering': ['created_at'], 'verbose_name': '대댓글', 'verbose_name_plural': '대댓글'},
        ),
        migrations.AlterModelOptions(
            name='recommentlike',
            options={'verbose_name': '대댓글 좋아요', 'verbose_name_plural': '대댓글 좋아요'},
        ),
        migrations.AlterModelOptions(
            name='recommentreport',
            options={'verbose_name': '대댓글 신고', 'verbose_name_plural': '대댓글 신고'},
        ),
    ]
