# Generated by Django 4.2.16 on 2025-02-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, '예약'), (2, '이벤트'), (3, '아카데미'), (4, '레슨'), (5, '프로모드'), (6, '기타')], default=6)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'faq',
                'ordering': ['id'],
            },
        ),
    ]
