# Generated by Django 4.2.20 on 2025-04-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ['deleted', '-required'], 'verbose_name': '약관', 'verbose_name_plural': '약관'},
        ),
        migrations.AlterModelOptions(
            name='agreementversion',
            options={'ordering': ['-created_at'], 'verbose_name': '약관 버전', 'verbose_name_plural': '약관 버전'},
        ),
    ]
