# Generated by Django 4.2.16 on 2024-11-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': '약관', 'verbose_name_plural': '약관'},
        ),
    ]
