# Generated by Django 4.2.16 on 2024-11-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_alter_agreement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={},
        ),
    ]
