# Generated by Django 4.2.16 on 2024-11-30 00:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_alter_agreement_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='content',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='useragreement',
            name='agreed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AgreementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agreements.agreement')),
            ],
            options={
                'db_table': 'agreement_versions',
                'ordering': ['-version'],
                'unique_together': {('agreement', 'version')},
            },
        ),
    ]
