# Generated by Django 4.2.16 on 2024-11-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_remove_agreement_content_remove_agreement_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='agreementversion',
            unique_together={('agreement', 'created_at')},
        ),
        migrations.RemoveField(
            model_name='agreementversion',
            name='version',
        ),
    ]
