# Generated by Django 4.2.16 on 2024-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0005_alter_agreementversion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
