# Generated by Django 4.2.16 on 2024-11-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0006_agreement_deleted_agreement_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementversion',
            name='summary',
            field=models.TextField(default='신규 생성'),
            preserve_default=False,
        ),
    ]
