# Generated by Django 4.2.16 on 2024-12-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0007_agreementversion_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ['deleted', '-required']},
        ),
    ]
