# Generated by Django 4.2.16 on 2025-01-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0008_alter_agreement_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAgreement',
        ),
    ]
