name: Coverage

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./sweep/yarn.lock"

      - name: Build
        run: |
          cd sweep
          yarn
          CI=true yarn test --coverage --watchAll=false

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./sweep/coverage/lcov.info
