name: Pylint

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      NAVER_API_KEY: ${{ secrets.NAVER_API_KEY }}
      NAVER_API_KEY_ID: ${{ secrets.NAVER_API_KEY_ID }}
      AWS_ACCESS_KEY: "AWS_ACCESS_KEY"
      AWS_SECRET_KEY: "AWS_SECRET_KEY"
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        sudo apt-get install graphviz graphviz-dev
        cd sweepseries
        pipenv install --dev

    - name: Analysing the code with pylint
      run: |
        cd sweepseries
        pipenv run pylint **/*.py --load-plugins pylint_django --django-settings-module=sweepseries.settings --rcfile=.pylintrc
        pipenv run pylint $(git ls-files '*.py') --rcfile=.pylintrc
